
alias php='/Applications/MAMP/bin/php/php7.3.24/bin/php -c "/Library/Application Support/appsolute/MAMP PRO/conf/php7.3.24.ini"'
alias pear='/Applications/MAMP/bin/php/php7.3.24/bin/pear'
alias pecl='/Applications/MAMP/bin/php/php7.3.24/bin/pecl'
alias composer='/Applications/MAMP/bin/php/composer'
alias python='/Applications/MAMP/Library/bin/python'
alias perl='/Applications/MAMP/Library/bin/perl'
alias cpan='/Applications/MAMP/Library/bin/cpan'
alias erb='/Applications/MAMP/Library/bin/erb'
alias gem='/Applications/MAMP/Library/bin/gem'
alias irb='/Applications/MAMP/Library/bin/irb'
alias rake='/Applications/MAMP/Library/bin/rake'
alias rdoc='/Applications/MAMP/Library/bin/rdoc'
alias ri='/Applications/MAMP/Library/bin/ri'
alias ruby='/Applications/MAMP/Library/bin/ruby'
alias rails='/Applications/MAMP/Library/bin/rails'
